# Generated by Django 5.1.6 on 2025-02-12 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_room_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.room'),
        ),
    ]
